import Head from "next/head";
import React from "react";
import { GetStaticProps, InferGetStaticPropsType } from "next";
import { Item } from "@components/projects";
import { projectApis } from "@/core/apis/project";
import { ProjectItem } from "@core/interface/project";

interface Props {
  list: ProjectItem[];
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  try {
    const res = await projectApis.getProjects();
    const result: ProjectItem[] = res?.result ? res.result : [];

    return {
      props: { list: result },
      revalidate: 60,
    };
  } catch (e) {
    console.log(e);
    return {
      props: { list: [] },
    };
  }
};

export default function Projects({
  list,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>이정주 포트폴리오</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center min-h-screen px-3 mb-10">
        {list &&
          list.map((d) => (
            <React.Fragment key={d.id}>
              <Item data={d} />
            </React.Fragment>
          ))}
      </div>
    </>
  );
}
